<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.8.1" />
        <PackageReference Include="xunit" Version="2.9.3"/>
        <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\SekaiToolsBase\SekaiToolsBase.csproj"/>
        <ProjectReference Include="..\SekaiToolsCore\SekaiToolsCore.csproj"/>
        <ProjectReference Include="..\SekaiToolsInfrastructure\SekaiToolsInfrastructure.csproj"/>
        <ProjectReference Include="..\SekaiToolsMedia\SekaiToolsMedia.csproj"/>
        <ProjectReference Include="..\SekaiDataFetch\SekaiDataFetch.csproj"/>
        <ProjectReference Include="..\SekaiToolsConfiguration\SekaiToolsConfiguration.csproj"/>
    </ItemGroup>
</Project>
