name: .net build

on:
  push:
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - 'Test'
  workflow_dispatch:

env:
  DOTNET_VERSION: '8.0.x' # The .NET SDK version to use
  BUILD_DIR: 'SekaiTools.Nightly'
  RESOURCE_DIR: 'resource'
  PROJECT_NAME: 'SekaiToolsGUI'
  SEVEN_ZIP_EXE: './resource/vapourSynth/7z.exe'

jobs:
  build:
    name: build-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest ]

    # Each job run contains these five steps
    steps:
      - uses: actions/checkout@v4

      - name: Get current date
        id: date
        run: echo "::set-output name=today::$(date +'%Y%m%d')"

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Dotnet Build
        run: |
          dotnet restore ${{ env.PROJECT_NAME }}
          dotnet build ${{ env.PROJECT_NAME }} --configuration Release --no-restore -o ${{ env.BUILD_DIR }}
      - name: Sort Artifacts
        run: |
          cp -r ${{ env.RESOURCE_DIR }} ${{ env.BUILD_DIR }}
          rm -r ${{ env.BUILD_DIR }}/runtimes/win-x86
          rm -r ${{ env.BUILD_DIR }}/runtimes/win-arm64
          rm -r ${{ env.BUILD_DIR }}/*.pdb  

      - uses: actions/upload-artifact@v4
        with:
          name: SekaiTools.Nightly.${{ steps.date.outputs.today }}
          path: ${{ env.BUILD_DIR }}