name: .net build

on:
  push:
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - 'Test'
  workflow_dispatch:

env:
  DOTNET_VERSION: '9.0.x' # The .NET SDK version to use
  BUILD_DIR: 'SekaiTools'
  PROJECT_NAME: 'SekaiToolsGUI'

jobs:
  build:
    name: build-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest ]

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          
      - name: Dotnet Build
        run: |
          dotnet restore ${{ env.PROJECT_NAME }}
          dotnet build ${{ env.PROJECT_NAME }} --configuration Release --no-restore -o ${{ env.BUILD_DIR }}
      - name: Sort Artifacts
        run: |
          rm -r ${{ env.BUILD_DIR }}/runtimes/win-x86
          rm -r ${{ env.BUILD_DIR }}/runtimes/win-arm64
          rm -r ${{ env.BUILD_DIR }}/*.pdb  

      - name: Zip the Build
        run: 7z a SekaiTools-${{ env.VERSION }}.7z ${{ env.BUILD_DIR }}/

      - name: Create Release and Upload Release Asset
        uses: actions/upload-artifact@v4
        with:
          name: SekaiTools-${{ env.VERSION }}.7z
          path: SekaiTools-${{ env.VERSION }}.7z